echo "auto lo"
echo ""
echo "iface lo inet loopback"
echo "iface eth0 inet dhcp"
echo ""
echo "allow-hotplug wlan0"
echo "auto wlan0"
echo "iface wlan0 inet static"
echo "address 192.168.2.2"
echo "netmask 255.255.255.0"
echo "wireless-mode ad-hoc"
echo "wireless-channel `~pi/get_pi_specific.py adhocnetchannel`"
echo "wireless-ap `~pi/get_pi_specific.py adhocnetbssid`"
echo "wireless-essid `~pi/get_pi_specific.py adhocnet`"
